### ISSUE TITLE
Undefined index: 0

### ISSUE THREAD

**Issue by Cannonb4ll** [Maatwebsite/Laravel-Nova-Excel#10]
First of al, great package, just what I needed! 🚀🤟

I keep getting a problem with some basic resources (whereas others work perfectly).

This is the error message:

```
Undefined offset: 0 at /Users/***/Workspace/***/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/DefaultValueBinder.php:56
```

My actions look like this:

```
    public function actions(Request $request)
    {
        return [
            (new DownloadExcel())->withHeadings('#', 'description')
        ];
    }
```

The columns does exist in the database, there is also no difficult eagerloading or anything else involved, its just a (really) basic orders table with id, description, total, user_id and timestamps.

More stacktrace:
```
[2018-08-31 05:56:19] local.ERROR: Undefined offset: 0 {"userId":1,"email":"email@email.com","exception":"[object] (ErrorException(code: 0): Undefined offset: 0 at /Users/***/Workspace/***/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/DefaultValueBinder.php:56)
[stacktrace]
#0 /Users/***/Workspace/***/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/DefaultValueBinder.php(56): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined offse...', '/Users/***...', 56, Array)
#1 /Users/***/Workspace/***/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/DefaultValueBinder.php(34): PhpOffice\\PhpSpreadsheet\\Cell\\DefaultValueBinder::dataTypeForValue(Array)
#2 /Users/***/Workspace/***/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Cell.php(184): PhpOffice\\PhpSpreadsheet\\Cell\\DefaultValueBinder->bindValue(Object(PhpOffice\\PhpSpreadsheet\\Cell\\Cell), Array)
#3 /Users/***/Workspace/***/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Worksheet/Worksheet.php(2508): PhpOffice\\PhpSpreadsheet\\Cell\\Cell->setValue(Array)
#4 /Users/***/Workspace/***/vendor/maatwebsite/excel/src/Sheet.php(208): PhpOffice\\PhpSpreadsheet\\Worksheet\\Worksheet->fromArray(Array, NULL, 'A13', false)
```

**Comment by patrickbrouwers** [comment]
Do you have an array/json column in there?

**Comment by Cannonb4ll** [comment]
Yes, there are 2 JSON columns (discount and transaction_data, both are also nullable). They are not registered in the `fields()` method though in Nova, not sure if this makes any difference.

**Comment by patrickbrouwers** [comment]
When you don't specify anything, it will take all `visible` attributes. You can limit it to the index fields with `->onlyIndexFields`, example: https://laravel-excel.maatwebsite.nl/nova/1.0/exports/customizations.html#exporting-all-index-columns

If you want more control, best to go for a dedicated export action with a `WithMapping` concern.

**Comment by Cannonb4ll** [comment]
Alright, will do, thanks 👍
