### ISSUE TITLE
[Question] Multiple customized exports on same Resource

### ISSUE THREAD

**Issue by FabioSTI** [Maatwebsite/Laravel-Nova-Excel#104]
### Prerequisites

* [X ] Able to reproduce the behaviour outside of your code, the problem is isolated to Laravel Excel.
* [X ] Checked that your issue isn't already filed.
* [X ] Checked if no PR was submitted that fixes this problem.

### Versions

* PHP version: 7.4.3
* Laravel version: 7.30.4
* Nova version: 3.6.0
* Package version: 1.2

### Description

Is it posible to have multiple customized exports on the same Nova resource ?
Currently I have: (Actually, same origin data, but different fields to be exported)

```
class ClaimsExport extends DownloadExcel implements  WithMapping
{ ...

```
and 

```
class BDXAllInfoIn extends DownloadExcel implements  WithMapping
{ ...
```

### Steps to Reproduce

Created 2 Nova Actions, extending DownloadExcel (implements  WithMapping)
Both included in the actions (Resource) array, by their own class names.

**Expected behavior:**

Two different actions listed  in Nova Resource's actions selector, each one generation its own export.

**Actual behavior:** 

In Nova's Action selector, I get two identical 'Download Excel' options. Both of them end exporting the first (ClaimsExport) one...

### Additional Information

I actually need several (additional) exports, with different fields based upon the same resource....

**Comment by patrickbrouwers** [comment]
Have you tried overruling the `public function name()` method? (Or setting the `public $name` property?)

**Comment by FabioSTI** [comment]
Hi Thanks. I'll check today.

**Comment by FabioSTI** [comment]
Worked like a charm!. Thanks.
