### ISSUE TITLE
Excel import issue in sheet index

### ISSUE THREAD

**Issue by shineraj-protracked** [Maatwebsite/Laravel-Nova-Excel#105]
hello, 
I am getting an error while trying to import one excel file.

exception: "ErrorException"
file: "/var/www/html/policy-engine/vendor/maatwebsite/excel/src/ChunkReader.php"
line: 55
message: "Undefined index: Worksheet"

php version : 7.4
laravel version : 8.30.*
laravel excel : latest

**Comment by patrickbrouwers** [comment]
Would need a bit more information. Also, are you sure you are reporting it to the right repo? This package only has resource exports. For bugs with the main package, you should use the https://github.com/Maatwebsite/Laravel-Excel issue tracker

**Comment by delia-curiel** [comment]
@shineraj-protracked hi, I am having the same issue.... did you resolve it?

**Comment by patrickbrouwers** [comment]
@delia-curiel this bug should be fixed if you are on the latest version of Laravel Excel and haven't specified your own version of phpspreadsheet (this bug is a 1.17 bug, Laravel Excel limits the install to 1.16)

**Comment by delia-curiel** [comment]
@patrickbrouwers that was exactly the issue. Thanks!
