### ISSUE TITLE
QUESTION Export the BelongsTo field with relationships column value

### ISSUE THREAD

**Issue by kristianharmer** [Maatwebsite/Laravel-Nova-Excel#109]
I am using the BelongsTo field and the display() function to show the relationships column value instead of the ID.

Example:

```
BelongsTo::make('Placeholder', 'Languagestring', \App\Nova\Languagestring::class)->viewable(false)->sortable()->display(function ($model) {
    return $model->placeholder;
}),
```

However, when I export I simply get the foreign key ID. Is there a way I can get the relationships column value like I do in the Nova view?

Best regards,
K...

**Comment by kristianharmer** [comment]
Please ignore me. This works out of the box. When viewing a Language I can go to the HasMany records for Translations at the bottom of the screen and then simply 'tick all fields' to be presented with the export action.

Prefect - thank you :)

**Comment by kristianharmer** [comment]
OK, I see your reference to here:

https://docs.laravel-excel.com/nova/1.0/exports/customizations.html#concerns

...this helped. However I didn't quite get it working but I found this which made the penny drop:

https://dor.ky/posts/2018/12/customising-exports-for-the-laravel-nova-excel-package/

Thanks for sharing this Laravel Nova package, much appreciated.

K...

**Comment by patrickbrouwers** [comment]
Hey @kristianharmer that's indeed the best way to do it. Feel free to PR the docs, if you have any improvements!
