### ISSUE TITLE
Files Not download

### ISSUE THREAD

**Issue by amit-insense** [Maatwebsite/Laravel-Nova-Excel#11]
Hello,
 I had Installed maatwebsite/laravel-nova-excel (1.0.1) .
Integrated  actions for Download Excel in my Nova Resources , no files downloaded . Message on Files showing .  Failed -No File .
See Attachement

No files downloaded .
![screenshot from 2018-09-03 12 55 56](https://user-images.githubusercontent.com/42092723/44973132-20bd9880-af79-11e8-9dd8-952985fe5127.png)

**Comment by amit-insense** [comment]
By adding below in app.php 
Maatwebsite\LaravelNovaExcel\LaravelNovaExcelServiceProvider::class,
Solved this Problem!

**Comment by patrickbrouwers** [comment]
Didn't the auto-discovery work? :(

**Comment by amit-insense** [comment]
Auto discovery is off in our project .

**Comment by patrickbrouwers** [comment]
Aha, that makes sense then :)

**Comment by patrickbrouwers** [comment]
Updated the docs to add a note about this.

**Comment by amit-insense** [comment]
Thanks :+1:

**Comment by packytagliaferro** [comment]
I am having this same issue. It just says "Failed - No File" in chrome. I have added the package manually in app.php, although auto discovery is on in my project, but still nothing. The response I get back from the package is:

```
download: "http://reflect.test/nova-vendor/maatwebsite/laravel-nova-excel/download?path=%2Fprivate%2Fvar%2Ftmp%2Flaravel-excel-9kHdcVh2sPrFf2vYUdgTsLmVpVW304ct&filename=users.csv"
name: "users.csv"
```

**Comment by GlennM** [comment]
> I am having this same issue. It just says "Failed - No File" in chrome. I have added the package manually in app.php, although auto discovery is on in my project, but still nothing. The response I get back from the package is:
> 
> ```
> download: "http://reflect.test/nova-vendor/maatwebsite/laravel-nova-excel/download?path=%2Fprivate%2Fvar%2Ftmp%2Flaravel-excel-9kHdcVh2sPrFf2vYUdgTsLmVpVW304ct&filename=users.csv"
> name: "users.csv"
> ```

Please create a new ticket with the issue template filled. The issue template is required for us to be able to help you and is automatically available for you when opening a new issue, please do not remove the contents of the issue template.
