### ISSUE TITLE
Customizing import modal

### ISSUE THREAD

**Issue by xoco70** [Maatwebsite/Laravel-Nova-Excel#115]
Hi, 

I already use the plugin to import Users in Laravel Nova. This works great.

Thing is I also use Laravel Nova Permissions, and the layout to import user changes depending on the user role.

So, I would like to add a link in the modal so that user can download the Excel layout before filling it. 

Is it possible to add text / link on the import modal ???

**Comment by patrickbrouwers** [comment]
Importing is not released yet, it's still in development. 

I don't think Nova allows editing the modal like that, but I'm not sure, it's not specific to this package I believe.

**Comment by xoco70** [comment]
Ok ! Thanks for the answer !
