### ISSUE TITLE
Action display tesxt 

### ISSUE THREAD

**Issue by kephren226** [Maatwebsite/Laravel-Nova-Excel#116]
Is there a way to change the action text by resource or translate it ?
I want to display de action text in french

**Comment by patrickbrouwers** [comment]
You can either translate it with `fr.json`. Or extend the class and overrule the `name()` method.

**Comment by kephren226** [comment]
> You can either translate it with `fr.json`. Or extend the class and overrule the `name()` method.

Thanks for taking time to reply
