### ISSUE TITLE
Not supporting laravel 8

### ISSUE THREAD

**Issue by abdulmoeed137** [Maatwebsite/Laravel-Nova-Excel#118]
Laravel 8 not supporting, Getting this error. 

Problem 1
    - maatwebsite/laravel-nova-excel[1.2.1, ..., 1.2.x-dev] require maatwebsite/excel ^3.1 -> satisfiable by maatwebsite/excel[3.1.0, ..., 3.1.x-dev].
    - maatwebsite/excel[3.1.28, ..., 3.1.30] require phpoffice/phpspreadsheet 1.16.* -> satisfiable by phpoffice/phpspreadsheet[1.16.0].
    - maatwebsite/excel[3.1.31, ..., 3.1.x-dev] require phpoffice/phpspreadsheet ^1.18 -> 
satisfiable by phpoffice/phpspreadsheet[1.18.0].
    - maatwebsite/excel 3.1.27 requires phpoffice/phpspreadsheet ^1.16 -> satisfiable by phpoffice/phpspreadsheet[1.16.0, 1.17.0, 1.17.1, 1.18.0].
    - maatwebsite/excel 3.1.26 requires phpoffice/phpspreadsheet ^1.15 -> satisfiable by phpoffice/phpspreadsheet[1.15.0, ..., 1.18.0].
    - maatwebsite/laravel-nova-excel 1.2.0 requires maatwebsite/excel 3.1.17 -> satisfiable by maatwebsite/excel[3.1.17].
    - phpoffice/phpspreadsheet[1.15.0, ..., 1.18.0] require ext-gd * -> it is missing from your system. Install or enable PHP's gd extension.
    - maatwebsite/excel[3.1.0, ..., 3.1.25] require php ^7.0 -> your php version (8.0.3) does not satisfy that requirement.
    - Root composer.json requires maatwebsite/laravel-nova-excel ^1.2 -> satisfiable by maatwebsite/laravel-nova-excel[1.2.0, ..., 1.2.x-dev].

**Comment by patrickbrouwers** [comment]
It is supporting PHP8, you are missing the gd extension according to composer

**Comment by alkrauss48** [comment]
This happened to me too; needed to install gd and then ext-zip as well, which fixed everything.
