### ISSUE TITLE
[QUESTION] i can't get action log when execute laravel nova excel

### ISSUE THREAD

**Issue by mlopezsti** [Maatwebsite/Laravel-Nova-Excel#128]
### Prerequisites

* [x] Able to reproduce the behaviour outside of your code, the problem is isolated to Laravel Excel.
* [x] Checked that your issue isn't already filed.
* [x] Checked if no PR was submitted that fixes this problem.

### Versions

* PHP version: 7.4
* Laravel version: 7.0
* Nova version: v3.6.0
* Package version: Laravel Nova Excel: 1.2

### Description

When I create a custom action and extended from DownloadExcel, Your module can't add a log line on the action log, as specifies "Laravel nova" on her documentation
Link documentation: https://nova.laravel.com/docs/3.0/actions/defining-actions.html#action-log.

I try to force to add this line with dispatch new action, but it not working.

**Expected behavior:**

When lauch Laravel excel, get action log or make possibility to access this funcionality.

**Actual behavior:** 

No action log

**Comment by patrickbrouwers** [comment]
Not supported

**Comment by mlopezsti** [comment]
But, I was try launch Action excel with dispatch and not working. For same?

**Comment by patrickbrouwers** [comment]
Laravel Excel completely takes over the Nova action, it's not possible to hook into that action log.

**Comment by mlopezsti** [comment]
Thanks
