### ISSUE TITLE
Method Laravel\Nova\Fields\FieldCollection::filterForIndex does not exist.

### ISSUE THREAD

**Issue by illambo** [Maatwebsite/Laravel-Nova-Excel#135]
https://github.com/SpartnerNL/Laravel-Nova-Excel/blob/891c21de17aafe6792f8582e8b4ee12942612cca/src/Requests/ExportLensActionRequest.php#L46

Hello, _filterForIndex_ method introduced in commit de423bd106bc73eacefd67b4cd74bd0339c91f2f is not available for laravel nova v2.12.0.

Reading the [requirements](https://docs.laravel-excel.com/nova/1.x/getting-started/installation.html#requirements) I find no limitations in the use of the nova version 2.x.
Correct? 

Thanks

**Comment by patrickbrouwers** [comment]
Feel free to PR support for 2.x
