### ISSUE TITLE
FileNotFound after upgrade

### ISSUE THREAD

**Issue by anditsung** [Maatwebsite/Laravel-Nova-Excel#138]
~~after upgrade from laravel 7 to laravel 8~~

when download excel file have the exception filenotfound

dont have problem on opening the file on storage/framework/cache/laravel-excel

**Comment by patrickbrouwers** [comment]
Not really clear what you are reporting.

**Comment by anditsung** [comment]
before add support for remote disk

```
protected function getDownloadUrl(BinaryFileResponse $response): string
```

after
```
protected function getDownloadUrl(string $filePath): string
```

i have a class that extend DownloadExcel to custom how it handle the download.
after the update i have FileNotFound Exception

**Comment by patrickbrouwers** [comment]
Overriding protected methods is always at own risk. Assuming you have figured out how to fix it for your code.
