### ISSUE TITLE
File doesn’t download in Firefox

### ISSUE THREAD

**Issue by RicLeP** [Maatwebsite/Laravel-Nova-Excel#14]
When using Firefox and running the DownloadExcel action no file is downloaded.

I am using 64.0a1 (2018-09-10) (64-bit) which is the nightly version which might be the problem. I don’t have the release version for testing.

**Comment by BengtHagemeister** [comment]
Same issue then #13

**Comment by patrickbrouwers** [comment]
Always try to check the open/closed issues before opening a new one. Like @BengtHagemeister says, it's duplicate of #13.
