### ISSUE TITLE
[BUG] ExportResourceActionRequest::forAllMatchingResources in Nova 4.0

### ISSUE THREAD

**Issue by olivervo** [Maatwebsite/Laravel-Nova-Excel#141]
### Prerequisites

* [x] Able to reproduce the behaviour outside of your code, the problem is isolated to Laravel Excel.
* [X] Checked that your issue isn't already filed.
* [X] Checked if no PR was submitted that fixes this problem.

### Versions

* PHP version: 8.1.3
* Laravel version: 9.6
* Nova version: 4.0.4
* Package version: 1.3

### Steps to Reproduce

After upgrading to Nova 4.0, the package caused a fatal error which was fixed in 1.3. However, I'm still running into the following error when exporting from an inline action in Nova.

`Method Maatwebsite\LaravelNovaExcel\Requests\ExportResourceActionRequest::forAllMatchingResources does not exist. {"userId":1,"exception":"[object] (BadMethodCallException(code: 0): Method Maatwebsite\\LaravelNovaExcel\\Requests\\ExportResourceActionRequest::forAllMatchingResources does not exist. at /vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:113)
`

**Comment by patrickbrouwers** [comment]
Best to provide a PR, I don't own a 4.0 license at the moment

**Comment by potsky** [comment]
@olivervo I have just replaced for the moment all actions by

```php
ExportAsCsv::make()
```

→ https://nova.laravel.com/docs/4.0/resources/#csv-export

**Comment by patrickbrouwers** [comment]
@olivervo let me know if the merge of #114 has fixed the issue for you. Tagged as 1.3.1

**Comment by mihaileu** [comment]
it works for me
