### ISSUE TITLE
"Select all"-download doesn't work

### ISSUE THREAD

**Issue by felixbessler** [Maatwebsite/Laravel-Nova-Excel#152]
* [ ] Able to reproduce the behaviour outside of your code, the problem is isolated to Laravel Excel.
* [x] Checked that your issue isn't already filed.
* [x] Checked if no PR was submitted that fixes this problem.

### Versions

* PHP version: 7.4.29 
* Laravel version: 8.83.16
* Nova version: 4.8.1
* Package version: 3.1.40 / 1.3.2

### Description

Index-page:
If you choose "select this page" and download it, it works perfectly. But if you choose "select all" I only get an empty page. 

### Steps to Reproduce

There are no steps to reproduce. It has the same error in every nova model. It breaks at Sheet.php -> fromQuery().

**Expected behavior:**

I'm expecting the download of a file.

**Actual behavior:** 

500 Error - white page.

**Comment by patrickbrouwers** [comment]
Cannot reproduce, please show me the stacktrace from the logs

**Comment by felixbessler** [comment]
I would love to but there is none. Logging works, I tested it but I don't get an error for that in the log files.

**Comment by patrickbrouwers** [comment]
Maybe in your php-fpm logs

**Comment by felixbessler** [comment]
`[20-Jun-2022 22:15:51 Europe/Berlin] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /Users/xxxx/dev/xxxx/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 262
[20-Jun-2022 22:15:51 Europe/Berlin] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 32768 bytes) in /Users/xxxx/dev/xxxx/vendor/symfony/error-handler/Error/FatalError.php on line 1
`

I found at least something but the memory_limit ist at 512MB and it is only a table with 109 entries. Does it help?

**Comment by patrickbrouwers** [comment]
According to the stacktrace it already fails when fetching all the data, before it even reaches the export

**Comment by felixbessler** [comment]
That is actually true. I will test it tomorrow and give you feedback about it. Thanks for now!

**Comment by felixbessler** [comment]
Okay, we found the "problem". In our local environment we need to change the memory_limit to about 2048MB or higher but we deployed a testversion in our staging environment and there it works with like 512MB. So yeah, it works, sorry to bother you and thank you!

**Comment by matthewjumpsoffbuildings** [comment]
Im having the same problem. I upped my local dev memory_limit to 2048, same error message
```
dev.ERROR: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 16457728 bytes) {"userId":1,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Allowed memory size of 2147483648 bytes exhausted (tried to allocate 16457728 bytes) at /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:158)
[stacktrace]
#0 {main}
```

**Comment by felixbessler** [comment]
We didn't looked deeper into it and just stopped showing the Download-Button when there are more than ~300k possible entries, even on staging/production.

That's all I can say about our "solution". But I would appreciate if there is a way to export a bigger file. Sometimes you have to do it, even though I understand the point that it is pretty "stupid". 🤷🏽
