### ISSUE TITLE
[BUG] MemoryCache class methods incompatible with Psr\SimpleCache\CacheInterface

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [Maatwebsite/Laravel-Nova-Excel#154]
### Prerequisites

* [X] Able to reproduce the behaviour outside of your code, the problem is isolated to Laravel Excel.
* [X] Checked that your issue isn't already filed.
* [X] Checked if no PR was submitted that fixes this problem.

### Versions
* PHP version: 8.1.4
* Laravel version: 9.33.0
* Nova version: 4.15.2
* Package version: 1.3.2

### Description

When attempting to install Laravel Nova Excel via Composer, I am getting the following error message:

```
Declaration of Maatwebsite\Excel\Cache\MemoryCache::get($key, $default = null) must be compatible with Psr\SimpleCache\CacheInterface::get(string $key, mixed $default = null): mixed

  at vendor/maatwebsite/excel/src/Cache/MemoryCache.php:62
     58▕ 
     59▕     /**
     60▕      * {@inheritdoc}
     61▕      */
  ➜  62▕     public function get($key, $default = null)
     63▕     {
     64▕         if ($this->has($key)) {
     65▕             return $this->cache[$key];
     66▕         }
```

### Steps to Reproduce

Attempt to install the package on the specified version of PHP

**Expected behavior:**

The package installs normally

**Actual behavior:** 

The package doesnt install, instead throwing the error message shared above

### Additional Information

If I manually edit the file in question (`Maatwebsite\Excel\Cache\MemoryCache.php`) and update the method signatures for almost all of the methods, to be compatible with the `Psr\SimpleCache\CacheInterface` , for example:
```php
 public function setMultiple($values, $ttl = null)
```
Becomes:
```php
 public function setMultiple($values, $ttl = null):bool
```
Then everything works fine and the generation of autoload files goes smoothly

**Comment by StanBarrows** [comment]
Probably linked to:

- [ ] https://github.com/SpartnerNL/Laravel-Excel/issues/3743

Temporary fix
`composer require psr/simple-cache:^2.0 maatwebsite/excel`

**Comment by patrickbrouwers** [comment]
Indeed has to be installed like that, the docs of the main package already reflected this, the Excel Nova docs too now.
