### ISSUE TITLE
Except does not work

### ISSUE THREAD

**Issue by drehimself** [Maatwebsite/Laravel-Nova-Excel#16]
Trying the example on a barebones version of Laravel 5.7.3 and Laravel Nova version 1.0.16. Get the following error.

<img width="679" alt="error" src="https://user-images.githubusercontent.com/4316355/45577318-60be2e80-b849-11e8-802d-ea3b626fba37.png">

```php
public function actions(Request $request)
{
    return [
        (new DownloadExcel)->except('email'),
    ];
}
```

Thanks!

**Comment by patrickbrouwers** [comment]
Version with except is not tagged yet. Documentation was already updated

**Comment by patrickbrouwers** [comment]
Released
