### ISSUE TITLE
[BUG] Crash with Nova 4.24.0; parameter type declaration mismatch in withName

### ISSUE THREAD

**Issue by Synchro** [Maatwebsite/Laravel-Nova-Excel#161]
* [x] Able to reproduce the behaviour outside of your code, the problem is isolated to Laravel Excel.
* [x] Checked that your issue isn't already filed.
* [x] Checked if no PR was submitted that fixes this problem.

### Versions

* PHP version: 8.2.5
* Laravel version: 10.9.0
* Nova version: 4.24.0
* Package version: 1.3.2, Laravel-Excel 3.1.48

### Description

After updating to Nova 4.24.0, I immediately started getting this crash:

    Symfony \ Component \ErrorHandler \ Error \ FatalError
    Declaration of Maatwebsite\LaravelNovaExcel\Actions\ExportToExcel::withName(string $name) must be compatible with Laravel\Nova\Actions\Action::withName($name)

### Steps to Reproduce

Straightforward inspection of the code shows this error is correct:

From LaravelNovaExcel:

```php
    public function withName(string $name)
    {
        $this->name = $name;

        return $this;
    }
```

From Nova:

```php
    public function withName($name)
    {
        $this->name = $name;

        return $this;
    }
```

While this could be fixed by removing the parameter type from the declaration, this is an inherited method that is otherwise unchanged, so it can just be deleted.

**Comment by Synchro** [comment]
BTW I've not checked if there are any other instances of this problem in the class.

**Comment by Synchro** [comment]
Update – I made this change manually, and Nova no longer crashes, so I think this is the only instance.

**Comment by patrickbrouwers** [comment]
Fix has been released
