### ISSUE TITLE
[BUG] nova 4.33: Post 404 not found

### ISSUE THREAD

**Issue by gtoto007** [Maatwebsite/Laravel-Nova-Excel#176]
### Prerequisites

* [X] Able to reproduce the behaviour outside of your code, the problem is isolated to Laravel Excel.
* [X] Checked that your issue isn't already filed.
* [X] Checked if no PR was submitted that fixes this problem.

### Versions

* PHP version: 8.2
* Laravel version: 10.x
* Nova version: 4.33
* Package version: 3.1.55

### Description

When I click on action Download Excel I have error " Post 404 Not Found" on  network tab of chrome.

<img width="1683" alt="Screenshot 2024-06-05 at 18 27 15" src="https://github.com/SpartnerNL/Laravel-Nova-Excel/assets/6715157/d0c36df2-d295-471f-aff5-aafe59e6fbe6">

I added this code in my nova resource:

```
use Maatwebsite\LaravelNovaExcel\Actions\DownloadExcel;
....
class Student extends Resource {
....
 public function actions(Request $request): array
    {
        return [new DownloadExcel()];
    }
 }
 :...
```

**Comment by patrickbrouwers** [comment]
Do other actions work on that page?

**Comment by gtoto007** [comment]
I have already deleted any other actions but the result is same.

Il giorno mer 5 giu 2024 alle 18:46 Patrick Brouwers <
***@***.***> ha scritto:

**Comment by patrickbrouwers** [comment]
I meant, if you add another action there, does it give a 404 on that action too or not?

**Comment by gtoto007** [comment]
I found out the issue  was caused by a field computed  in Student Resource. I fixed it and than I can download excel with success.
