### ISSUE TITLE
Request for lens support 

### ISSUE THREAD

**Issue by dillingham** [Maatwebsite/Laravel-Nova-Excel#20]
When downloading from a [nova lens](https://nova.laravel.com/docs/1.0/lenses/defining-lenses.html), it does not use the lens columns but rather the main resource

The reason I think this is important to address is

1. The user would expect the file to contain what they see
2. Provides solution to downloading multiple formats of the resource data

I figured a work around to making a custom file for a specific case would be lenses

VERY useful to say "Go to lens > select specific export lens > click download action"

**Comment by patrickbrouwers** [comment]
Lenses are supported. You have to call `->onlyIndexFields()` to let it select all index fields that are defined on that lens (https://laravel-excel.maatwebsite.nl/nova/1.0/exports/customizations.html#exporting-all-index-columns)

**Comment by patrickbrouwers** [comment]
Next release will do `onlyIndexFields()` be default. Possible to customize with `only` or `except` (or `allFields`)

**Comment by dillingham** [comment]
@patrickbrouwers oh awesome! Completely overlooked that haha :)

That would be so great if it were the default! That was my initial expectation, feels natural.

Related issue, I made some dynamic columns like so

```php

public static function query(LensRequest $request, $query)
{
    return $request->withOrdering($request->withFilters(
        $query->select([
            'id',
            \DB::raw('YEAR(`created_at`) AS `year`'),
            \DB::raw('QUARTER(`created_at`) AS `quarter`'),
            \DB::raw('MONTHNAME(`created_at`) AS `month`'),
        ])
    ));
}
```

and it threw the following sql related error

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'year' in 'field list' (SQL: select `id`, `year`, `quarter`, `month` ...etc
```
Although it displays as intended, the query for excel seems to be using fields vs query or something

**Comment by patrickbrouwers** [comment]
Can you please open a new issue for that, so we won't loose track of it.
