### ISSUE TITLE
Lens query and raw select statements

### ISSUE THREAD

**Issue by dillingham** [Maatwebsite/Laravel-Nova-Excel#21]
Nova v1.0.16 & Nova Excel v1.0.4

When using lenses as described in the [nova docs](https://nova.laravel.com/docs/1.0/lenses/defining-lenses.html) and adding columns like so

```php
public static function query(LensRequest $request, $query)
{
    return $request->withOrdering($request->withFilters(
        $query->select([
            'id',
            \DB::raw('YEAR(`created_at`) AS `year`'),
            \DB::raw('QUARTER(`created_at`) AS `quarter`'),
            \DB::raw('MONTHNAME(`created_at`) AS `month`'),
        ])
    ));
}
```
```php
public function fields(Request $request)
{
    return [
        ID::make('ID', 'id')->sortable(),
        Text::make('Year')->sortable(),
        Text::make('Quarter')->sortable(),
        Text::make('Month')->sortable(),
    ];
}
```

Although it displays as intended, the downloaded file only includes the ids

The raw selects are empty in the resulting file

**Comment by patrickbrouwers** [comment]
Can you specify your Laravel Nova Excel version.

**Comment by dillingham** [comment]
@patrickbrouwers I was using v1.0.3 but updated to v1.0.4 and tested this issue

I updated the issue to reflect that the mysql error is no longer present

But the file that does download doesn't include the raw select values

**Comment by patrickbrouwers** [comment]
Can you show your export action.

**Comment by patrickbrouwers** [comment]
It's most likely due to the fact that `year`, etc. aren't part of the "index fields" of the resource. Try using `->only()` e.g.

**Comment by dillingham** [comment]
Initially was  `(new DownloadExcel)->onlyIndexFields()` as described to get custom fields to show

Is also empty when changed it to `(new DownloadExcel)->only('id', 'year', 'month', 'quarter')`

**Comment by patrickbrouwers** [comment]
Can you try: `(new DownloadExcel)->allFields()->only('id', 'year', 'month', 'quarter')`

**Comment by dillingham** [comment]
Also missing the values for raw selects and only including id values

**Comment by patrickbrouwers** [comment]
I'll have a look at it later

**Comment by patrickbrouwers** [comment]
@dillingham Think I got it working, can you test with `1.0.*@dev` ?

**Comment by dillingham** [comment]
@patrickbrouwers indeed you have! tested just as `new DownloadExcel,` no only etc and it works!

**Comment by patrickbrouwers** [comment]
Tagged a release. Thanks for testing

**Comment by dillingham** [comment]
Thank you so much for fixing
