### ISSUE TITLE
array_flip(): Can only flip STRING and INTEGER values!

### ISSUE THREAD

**Issue by shopapps** [Maatwebsite/Laravel-Nova-Excel#24]
Hi,

When trying to Export to Excel (via a Lens), I am seeing an error:

    array_flip(): Can only flip STRING and INTEGER values!

any thoughts what can cause this?

**Comment by patrickbrouwers** [comment]
We don't use an `array_flip` in our code. It's most likely something in your or Nova's code. Can you provide a bit more information. This is quite limited to work with. Think about code example, full stacktrace etc.

**Comment by shopapps** [comment]
Hi,  

Yeah I knew it was a general question, I was just curious if anyone had seen something similar before and could give me a direction to look.  

I will see what bits of the code I can sanitise and release.  But it is a standard Lens and Filter setup, with a couple of columns created not from the direct SQL query and shows fine on the VueJS Table...

**Comment by shopapps** [comment]
After some digging around the issue seems to be around Nova's callbacks in Computed Fields. i.e. using:

```php
 Text::make('Colour', function() {
                return $this->getCurrentOptionValue('Colour');
            }),
```
or even just...
```php
 Text::make('Colour', function() { return ''; }),
```

in the fields() method causes the issue.  Don't see this as an issue with laraval-nova-excel persay just means anyone using callbacks cant use the module for that specific resource/Lens :-(

Regards,

Paul.

**Comment by patrickbrouwers** [comment]
Hm, perhaps we can figure something out to get the value that the callback creates, but I'm not sure on which level this goes wrong. Let's leave the ticket open, I will have a look at it soon.

**Comment by patrickbrouwers** [comment]
WIP https://github.com/Maatwebsite/Laravel-Nova-Excel/pull/26. Feel free to give it a test.

**Comment by shopapps** [comment]
Great thanks, will take a look in the next few days and let you know! 👍

**Comment by patrickbrouwers** [comment]
Computed fields are released as 1.1

**Comment by arditokshtuni** [comment]
@patrickbrouwers i am getting this error because i use this field on my nova resource https://github.com/dillingham/nova-button

Is there any option to exclude this filed in case to avoid error?

Thanks, great package btw

**Comment by BasselArt** [comment]
> @patrickbrouwers i am getting this error because i use this field on my nova resource https://github.com/dillingham/nova-button
> 
> Is there any option to exclude this filed in case to avoid error?
> 
> Thanks, great package btw

Same here

**Comment by noahlocke** [comment]
> @patrickbrouwers i am getting this error because i use this field on my nova resource >https://github.com/dillingham/nova-button
>
>Is there any option to exclude this filed in case to avoid error?
>
>Thanks, great package btw

me too @patrickbrouwers
