### ISSUE TITLE
[BUG] Lens download query using id when lens doesn't

### ISSUE THREAD

**Issue by dillingham** [Maatwebsite/Laravel-Nova-Excel#25]
### Prerequisites

* [x] Able to reproduce the behaviour outside of your code, the problem is isolated to Laravel Excel.
* [x] Checked that your issue isn't already filed.
* [x] Checked if no PR was submitted that fixes this problem.

### Versions

* PHP version: 7.2
* Laravel version: 5.7
* Nova version: 1.1.3
* Package version: 1.0.6

### Description

The following error prevents lenses from being downloaded when joins & aggregation.
It seems the download action isn't using an identical query for lenses maybe

### Steps to Reproduce

Make a query that doesn't group by the parent id
This lens is attached to an "orders" resource
And it gets the number of orders and the sum
The order id is unrelated and excluded
Which does not pose an issue for nova lenses

```php
public static function query(LensRequest $request, $query)
{
    return $request->withOrdering($request->withFilters(
        $query
            // ->select('orders.id')
            ->addSelect('teams.name as team_name')
            ->addSelect(\DB::raw('count(orders.id) as orders_count'))
            ->addSelect(\DB::raw('sum(orders.total) as spend'))
            ->join('teams', 'orders.team_id', '=', 'teams.id')
            ->groupBy('teams.id')
    ));
}
```
**Expected behavior:**

Export the table with a join, aggregate & group by 

**Actual behavior:** 

Throws exception stating parent table id isn't included in the group by 

```
[2018-09-28 10:02:29] local.ERROR: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'databasename.orders.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by (SQL: select `teams`.`name` as `team_name`, count(orders.id) as orders_count, sum(orders.total) as spend from `orders` inner join `teams` on `orders`.`team_id` = `teams`.`id` where `orders`.`id` in () group by `teams`.`id` order by `orders`.`id` asc limit 200 offset 0) 
```

### Additional Information

A lens is a report table. Not always will the id be assumed. 
Most cases it will likely not be.

**Comment by patrickbrouwers** [comment]
Will look into it soon.

**Comment by patrickbrouwers** [comment]
@dillingham I'm getting the same exception when just loading the Lens view. 
Without the groupBy the export works because of WIP #26 and #22

**Comment by dillingham** [comment]
@patrickbrouwers it seems as though I placed my action on the wrong resource.
I am getting the error because the resource.id should the resource the lens belongs to
I had an Orders resource and added OrdersByTeams, thus an orders.id was wrongly included
But it should be Teams resource, where an teams.id is rightfully included

In short, the solution you produced works perfectly when I implement nova properly 👍 

Thank you so much for adding this feature

**Comment by patrickbrouwers** [comment]
I'm glad to hear that!
