### ISSUE TITLE
Download doesn't apply sort order

### ISSUE THREAD

**Issue by bbrala** [Maatwebsite/Laravel-Nova-Excel#27]
### Prerequisites

* [ ] Able to reproduce the behaviour outside of your code, the problem is isolated to Laravel Excel.
* [x] Checked that your issue isn't already filed.
* [x] Checked if no PR was submitted that fixes this problem.

### Versions

* PHP version: 7.2
* Laravel version: 5.7
* Nova version: 1.1.4
* Package version: 1.0.6

### Description

When exporting the sort order of the overview is not kept. This makes exporting large lists quite hard.

### Steps to Reproduce

Resource with 200 records, order by a value, set per page to 100, download.

**Expected behavior:**

Download the top 100 (in order)

**Actual behavior:** 

It downloads the 10 ordered by ID

**Comment by patrickbrouwers** [comment]
Yes, that's a known issue. Nova doesn't pass the order information to the action, so we don't know on what to sort.

**Comment by bbrala** [comment]
Hmm, would it be possible to just export all items then, since currently any selection is completely random probably. Although i'm not too sure what you get passed regarding the current selection. I did also press the select all checkboxes to find out of that would download the whole set, but it didn't. 

Perhaps serving also being able all records would be a way to at lease make it working fo large sets?

**Comment by patrickbrouwers** [comment]
When I select certain rows, it exports the correct ones for me. Both select all and select all matching work as expected for me. It only doesn't respect the ordering I gave it.

Not sure I understand your last suggestion? What do you mean with serving?

**Comment by bbrala** [comment]
Hmm, ill double check if i overlooked something then if select all works for you.

I just read my last sentence, and that is not even close to real English, sorry, ignore it for now. I'll get back to you in a bit.

**Comment by bbrala** [comment]
Ok, just tested, and "select all matching" works as expected, so apparently i didn't test that correctly.

Regarding the order, guess we just need to wait for an update to nova then :)

Thanks for the quick responses.

**Comment by patrickbrouwers** [comment]
Yes, it should work straight away when nova starts passing it.
