### ISSUE TITLE
Malformed UTF-8 characters, possibly incorrectly encoded

### ISSUE THREAD

**Issue by batFormat** [Maatwebsite/Laravel-Nova-Excel#28]
I get an error when starting the download action.

### Versions

* PHP version:  7.2 
* Mysql version:  5.7.22 
* Database encoding:  UTF-8 unicode
* Laravel version: 5.7 
* Nova version:  1.1.17
* Package version: 3.1 and 1.0

### Description

I used the quick instructions and installed the package.
Added an action to one of my entities.
When I press download, I receive a message
"Malformed UTF-8 characters, possibly incorrectly encoded"

P.S.

In the database I use Cyrillic

**Comment by patrickbrouwers** [comment]
Please post full stack trace of the error.

**Comment by batFormat** [comment]
> Please post full stack trace of the error.

https://gist.github.com/batFormat/b2a31ee655ea068120e0ba2218ffd41b

**Comment by patrickbrouwers** [comment]
Based on the stacktrace I can't see anything that this package causes. You should try to debug what causes laravel's JsonResponse class causes.

**Comment by batFormat** [comment]
> Based on the stacktrace I can't see anything that this package causes. You should try to debug what causes laravel's JsonResponse class causes.

I solved this problem.

When I dumped, `Maatwebsite\Excel\Excel`, download method.
I saw that the file name consists of the wrong encoding.

In download method.

```
 /**
     * {@inheritdoc}
     */
    public function download($export, string $fileName, string $writerType = null)
    {
        $file = $this->export($export, $fileName, $writerType);

        dd($this->response->download($file, $fileName)); 

        return $this->response->download($file, $fileName);
    }
```

Part dump.

```
 "content-disposition" => array:1 [
      0 => "attachment; filename=__________________.xlsx; filename*=utf-8''ðŸð°ñ€ð°ð¼ðµñ‚ñ€ñ‹.xlsx"
  ]
```

So I took a method from the documentation to set the file name, and it worked for me.
`->withFilename('users-' . time() . '.xlsx')`
Thanks for the help!

**Comment by patrickbrouwers** [comment]
Great! Perhaps always make sure the filename you pass is UTF-8 encoded. You could use `Str::ascii()`
