### ISSUE TITLE
Export to PDF - using MPDF 

### ISSUE THREAD

**Issue by gavnyx** [Maatwebsite/Laravel-Nova-Excel#30]
I got this error when export to PDF

local.ERROR: unlink(C:\Users\user\AppData\Local\Temp\qtsingleapp-lineex-3e70-1-lockfile): Resource temporarily unavailable

- I was install mpdf package
- Publish excel config
- Change config temp_path to another folder (not system temp folder)

**---- To fix this issue as my temporary solution ----**

1. Open file ...\vendor\mpdf\mpdf\src\Cache.php
2. Add this code to __construct
`
public function __construct($basePath, $cleanupInterval = 3600)
	{
		if (!$this->createBasePath($basePath)) {
			throw new \Mpdf\MpdfException(sprintf('Temporary files directory "%s" is not writable', $basePath));
		}

		$this->basePath = config('excel.exports.temp_path', $basePath); // <-- I add this code

		$this->cleanupInterval = $cleanupInterval;
	}
`
**with this code, I can export as PDF file.**
---
How to fix this issue and not hardcoded core source?
Thank you...

**Comment by patrickbrouwers** [comment]
Haven't tested it, but I think you should use: `PhpOffice\PhpSpreadsheet\Shared\File::setUseUploadTempDirectory(your_path)`

**Comment by gavnyx** [comment]
@patrickbrouwers Where I should use that code?

**Comment by patrickbrouwers** [comment]
@muswanto you can put it anywhere you want, e.g. in a service provider.
