### ISSUE TITLE
Select All Matching not support Pivot Actions

### ISSUE THREAD

**Issue by wiwatsrt** [Maatwebsite/Laravel-Nova-Excel#31]
### Versions

* PHP version: 7.2
* Laravel version: 5.7
* Nova version: 1.18
* Package version: 1.1

### Description

If **Select All Matching** action not display but **Select All** it 's work

**Comment by wiwatsrt** [comment]
Ref.
https://nova.laravel.com/docs/1.0/actions/registering-actions.html#pivot-actions

**Comment by patrickbrouwers** [comment]
@wiwatsrt from your description I can only gather that this is not really a problem related to this package, but to Laravel Nova in general. If this is not the case please provide a bit more information, code samples, screenshots.
