### ISSUE TITLE
Column Merging

### ISSUE THREAD

**Issue by ssx** [Maatwebsite/Laravel-Nova-Excel#32]
Hi!

Firstly, great product. It's been an absolute time-saver for some of our projects.

In the normal version of the Excel lib, we can merge some of the output columns together but have looked through the docs and source, it doesn't seem to be possible in the Nova version - is that correct?

**Comment by patrickbrouwers** [comment]
You'll have to use a custom action class extending ours. In there you can use any methods/concerns of the normal version of the lib. See: https://laravel-excel.maatwebsite.nl/nova/1.0/exports/customizations.html#full-control

**Comment by ssx** [comment]
Hi @patrickbrouwers! I ended up doing exactly that, I'm just writing a blog post on how to accomplish it so I'll stick the link here in case anyone else wants to do just that.

**Comment by patrickbrouwers** [comment]
Great! :)
