### ISSUE TITLE
Computed Fields not properly included

### ISSUE THREAD

**Issue by jkudish** [Maatwebsite/Laravel-Nova-Excel#36]
### Prerequisites

* [x] Able to reproduce the behaviour outside of your code, the problem is isolated to Laravel Excel.
* [x] Checked that your issue isn't already filed.
* [x] Checked if no PR was submitted that fixes this problem.

### Versions

* PHP version: 7.2
* Laravel version: 5.7.15
* Nova version: 1.2.0
* Package version: 1.1.1

### Description

Computed fields are only included for certain resources, but not others. Haven't been able to determine why.

### Steps to Reproduce

Example:

* In Nova: https://dsc.cloud/sparkdev/Screen-Shot-2018-12-17-11-22-20.32
* In Excel: https://dsc.cloud/sparkdev/Screen-Shot-2018-12-17-11-23-36.26

**Expected behavior:**

All the field values to be added into the export.

**Actual behavior:** 

Computed fields not properly added into the export.

### Additional Information

This seems to happen when there's pagination involved (exporting about 200 items)

**Comment by patrickbrouwers** [comment]
Can you retest this with the 1.1.2 release

**Comment by jkudish** [comment]
Will do, thanks @patrickbrouwers !

**Comment by jkudish** [comment]
Seems to be working with 1.1.2, thank you!
