### ISSUE TITLE
[QUESTION] Is there any plan to extend this to include an import action for resources?

### ISSUE THREAD

**Issue by MichaelCrowcroft** [Maatwebsite/Laravel-Nova-Excel#38]
I'm looking to use CSV files as a sort of bulk upload option and was wondering if that's a feature that is planned at all for this package, I know the base Laravel Excel package handles this already.

If it's not planned I will work on my own implementation, if it is planned I would be happy to contribute in some way.

**Comment by patrickbrouwers** [comment]
Hey @MichaelCrowcroft , it's planned, but might take a while before it will be released.

**Comment by hulkhogan** [comment]
> 
> 
> Hey @MichaelCrowcroft , it's planned, but might take a while before it will be released.

Any idea for the release date (couple of weeks or couple of months)?
I'm waiting for this feature as well :)

**Comment by patrickbrouwers** [comment]
Can't put a date on it yet. Won't be for January for sure.

**Comment by MichaelCrowcroft** [comment]
No worries @patrickbrouwers good to know it's planned thanks!

**Comment by christophrumpel** [comment]
Also looking forward to the `import` feature :-) 👍

**Comment by simonhamp** [comment]
I've been working on [this little import tool](https://novapackages.com/packages/simonhamp/laravel-nova-csv-import) for a while. Finally got it to a point where it was ready for release the other day. It's in active development, but desperate for some battle-testing. Hope you'll give it a go!

**Comment by patrickbrouwers** [comment]
Looking good @simonhamp ! Does it only work for csv?

**Comment by simonhamp** [comment]
@patrickbrouwers for now, but keen to widen that scope and make it cater for more
