### ISSUE TITLE
[QUESTION] Export Excel with same data displayed

### ISSUE THREAD

**Issue by stezani** [Maatwebsite/Laravel-Nova-Excel#39]
### Prerequisites

* [ ] Able to reproduce the behaviour outside of your code, the problem is isolated to Laravel Excel.
* [ X] Checked that your issue isn't already filed.
* [ X] Checked if no PR was submitted that fixes this problem.

### Versions

* PHP version: 7.1.25
* Laravel version: 5.7
* Nova version: latest
* Package version: latest

### Description

Hi! Thank you for this time saver plugin. I have a question about his behaviour: i'm looking for export in excel a nova resource called that is a report with a lot of fields that are connected with foreign keys to other tables. Now in my nova resource page i can see the description of each row connected with keys in my report but if i click export to excel i have a single row with only foreign keys: can i have instead the description like in browser? 

### Steps to Reproduce

Create a resource in relation with others and add a relation field (like BelongsTo)

**Expected behavior:**

Show description of related resource

**Actual behavior:** 

Show the foreign key to related resource

**Comment by patrickbrouwers** [comment]
@stezani I do remember this working. Are you on package version 1.1.* ? See my blog post about it: https://medium.com/maatwebsite/laravel-nova-excel-1-1-ready-for-launch-37e0ff1aef06

**Comment by stezani** [comment]
Hi @patrickbrouwers thank you for your reply. Yes i have in my composer.json the 1.1.^ version. But when i export my excel i have only the foreign keys and not the description.
<img width="1792" alt="tableindex" src="https://user-images.githubusercontent.com/12540345/52225716-5c071f00-28ab-11e9-975a-bb628d38de50.png">
<img width="1792" alt="export" src="https://user-images.githubusercontent.com/12540345/52225770-79d48400-28ab-11e9-812f-aef0c0c7dac9.png">

**Comment by patrickbrouwers** [comment]
Can you show me your code? The `new DownloadExcel()` part in the actions array. It seems you are selecting columns?

**Comment by stezani** [comment]
Hi @patrickbrouwers, here my actions function
```
/**
     * Get the actions available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function actions(Request $request)
    {
        return [
            (new DownloadExcel)->withHeadings()->allFields()->askForFilename()->askForWriterType()
        ];
    }
```
Thank you for your help

**Comment by patrickbrouwers** [comment]
Try to remove `->allFields()`. Without `allFields()` it will take exactly what's on your resource index.

**Comment by stezani** [comment]
Ok it's my problem, i have insert `OnlyOnForm` and `OnlyOnDetail` restrictions in my fields. If i remove them it all works. Thank you

**Comment by patrickbrouwers** [comment]
Glad you figured it out :)
