### ISSUE TITLE
[QUESTION] Export related models

### ISSUE THREAD

**Issue by simonedelmann** [Maatwebsite/Laravel-Nova-Excel#41]
### Prerequisites
* [X] Able to reproduce the behaviour outside of your code, the problem is isolated to Laravel Excel.
* [X] Checked that your issue isn't already filed.
* [x] Checked if no PR was submitted that fixes this problem.

### Versions
* PHP version: 7.3
* Laravel version: 5.7
* Nova version: 1.3.1
* Package version: - current -

### Description
Actually this is no issue but a question. I have two models: Projects, Members. Each project has many members. 

What I want to do? I want to export a list (xlsx) of all members for one project. I've created a Member's action. Then I have to select all members and run my action.

What I want to do instead? I want to run an action on a single project, getting all members. It this possible?

If this is the wrong place for questions like this, I apologize. Thank you for your help!

**Comment by patrickbrouwers** [comment]
I think it's possible to execute an action on a relation resource. Create a hasMany field for Project -> Members and then if you go to show Project, you should see a list of Members. If you have a Member Excel action, then it should be there to execute.

**Comment by simonedelmann** [comment]
@patrickbrouwers Thank you! Yes, this is exactly how I'm doing that. 
I'm sorry, I wasn't clear. For better user experience I would like to skip the select-all step. Let me explain a little more:

If I'm managing a project I (almost always) want to have a list of all active members. I've created a filter for that. So now I have to do lots of things to get the list:
1. Open the project's detail view.
2. Choosing the correct filter.
3. Selecting all (filtered) members
4. Select Member's Excel action.
5. Run the action.

What I would prefer:
1. Open the project's detail view / Selecting project in project index view.
2. Run action on project.

I'm sorry for the ugly English, I'm not a native speaker. I hope, it gets clear now, what I want to do. 

Thank you very much for your help!

**Comment by patrickbrouwers** [comment]
@simonedelmann the "select-all" step is a Nova thing, so we can't really do a lot about that. Currently Nova only allows us to run actions on selected rows.

**Comment by simonedelmann** [comment]
OK. :( Anyway thank you very much!

**Comment by larshanskrause** [comment]
Similar question here (and staying in Simons example): when I use an excel export action on members via the the detail view of projects (members as relation resource on a HasMany-Field), the export ignores all selections and filters I apply to the relation resources before. No matter how many members I select for my export, I always get all related members in my excel file. However, if I run this action on the index view of members it works just fine and respects my selections for the export. Any idea what's going on here, @patrickbrouwers ? I use the WithMapping concern btw. Many thanks!

**Comment by patrickbrouwers** [comment]
I think it's easier to just call Laravel Excel directly in a Nova action in those cases.

**Comment by ThisIsMyFavouriteJar** [comment]
I faced the same issue, and I found a way around this. By implementing FromQuery in your action as well, and passing the resource variable to the action you can create a custom query. My result looks something like this:

`class ExportUsers extends DownloadExcel implements FromQuery, WithMapping, WithHeadings
{
    public $onlyOnDetail = true;

    public function __construct(Request $request)
    {
        $this->project_id = $request->get('resources');
    }

    public function query()
    {
        return Users::where('project_id', $this->project_id);
    }

    public function map($product): array
    {       
            return [
               $user->name,
               $user->project->name
            ];
    }

}`

Assuming that there is 1 project with many users.
