### ISSUE TITLE
Using allFields() method breaks export of relationship and computed fields

### ISSUE THREAD

**Issue by duncmc** [Maatwebsite/Laravel-Nova-Excel#48]
### Prerequisites

* [X] Able to reproduce the behaviour outside of your code, the problem is isolated to Laravel Excel.
* [X] Checked that your issue isn't already filed.
* [X] Checked if no PR was submitted that fixes this problem.

### Versions

* PHP version: 7.2.14
* Laravel version: 5.8.10
* Nova version: 2.0.1
* Package version: 3.1.11 and 1.1.3

### Description

Using `allFields()` method breaks export of relationship and computed fields.

### Steps to Reproduce

Ensure that your Resource includes a field that is defined with a `BelongsTo` relationship… 

    BelongsTo::make('User'),

…or field that returns a computed value…

    Text::make('Random number', function () {
        return str_random();
    }),

Use the `allFields()` method on the action as described in the documentation…

    public function actions(Request $request)
    {
        return [
            (new DownloadExcel)->allFields(),
        ];
    }

**Expected behavior:**

The exported file should contain a representation of the relationship similar to how it appears on the Nova Resource index page. Similarly the file should contain the output generated by closure defined on the computed field.

**Actual behavior:** 

The related record is represented in the Excel file as a foreign key. Computed fields are omitted.

### Additional Information

This is already a known issue as indicated by a common made on a previous issue.

> Are you using `->allFields()` perhaps?

> _Originally posted by @patrickbrouwers in https://github.com/Maatwebsite/Laravel-Nova-Excel/pull/26#issuecomment-435132732_

Given that the dev team has been aware of this since at least November 2018 I assume it is difficult or impractical to fix. **However it would be useful to have this “feature” documented on the "[Customizing Exports](https://docs.laravel-excel.com/nova/1.1/exports/customizations.html#with-headings)” page of the documentation and anywhere else that may be relevant.**

**Comment by patrickbrouwers** [comment]
`allFields` is a bit of a wrong naming. What it actually does is getting all "attributes" from the Eloquent model and doesn't consult the Nova resource to see what kind of field it is. 

I'll probably deprecate and replace this method in the next release by `allAttributes` to align with the actual functionality. 

If you want to have an export that represents how the nova resource index page looks, you should just not using `allFields` at all and it should work out of the box.

**Comment by pelmered** [comment]
> `allFields` is a bit of a wrong naming. What it actually does is getting all "attributes" from the Eloquent model and doesn't consult the Nova resource to see what kind of field it is.
> 
> I'll probably deprecate and replace this method in the next release by `allAttributes` to align with the actual functionality.
> 
> If you want to have an export that represents how the nova resource index page looks, you should just not using `allFields` at all and it should work out of the box.

What should I do if I want to include all fields including relationships and computed values?

**Comment by patrickbrouwers** [comment]
@pelmered with "all fields" do you mean all fields that are defined as "index" fields on the nova resource? Than you don't have to do anything, those are used by default.

**Comment by pelmered** [comment]
@patrickbrouwers No, all fields that are defined on the resource no matter where they are displayed. In my case I would like to include all those fields except one. 

I think this is the most common use case, because you probably want to avoid side scrolling to use the buttons on the row.

**Comment by patrickbrouwers** [comment]
I think currently you would have to specify all fields with `->only()` that you want in the export. 
We might need to change `allFields` to do that instead. Feel free to PR that functionality. Happy to incorporate it as a solution in the package.

**Comment by ghost** [comment]
+1 on the ability to have a true allFields functionality!

**Comment by xoco70** [comment]
Same here. If using only(), when having a relationship with user_id, I can use user that will display the whole json object, but not user.email

**Comment by patrickbrouwers** [comment]
PR was merged
