### ISSUE TITLE
[BUG] Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by gmarineau** [Maatwebsite/Laravel-Nova-Excel#49]
### Versions

* PHP version: 
* Laravel version: v5.7.28
* Nova version: v1.3.2
* Package version: 3.1.11 - 1.1.3

### Description

Hi,

I have a simple resource with three fields and when I try to Download the excel. I get this message

> Invalid argument supplied for foreach()

When I the code this variable is always null in the ExportToExcel class : 

> $this->actionFields;

### Steps to Reproduce

Install the package, add the action in the resource and test to Download Excel.

I have try on different resources and same bug each time.

### Additional Information

If in the package when I try to change the ExportExcel class and replace the 

> return $this->actionFields;

by this it's work

return [];

**Comment by mrigo** [comment]
Same here.
Any solutions?

Thanks

**Comment by nysso** [comment]
any solution for this guys ?

**Comment by mrigo** [comment]
I saw that my problem was related to another Laravel nova packages, [https://novapackages.com/packages/epartment/nova-dependency-container](Nova Field Dependency Container), great package but I removed it because of this bug :(
Without it, this works fine!

**Comment by gmarineau** [comment]
Okay thank's, I have created a custom Action with the same function than the package to export with Excel

**Comment by patrickbrouwers** [comment]
I couldn't reproduce the issue, will try with adding that package and see if there's anything we can do from this package to make them compatible.

**Comment by nysso** [comment]
I confirm what @mrigo said, it was this package:
https://novapackages.com/packages/epartment/nova-dependency-container
I uninstalled it and everything worked great

**Comment by patrickbrouwers** [comment]
Workaround released as 1.1.4
