### ISSUE TITLE
Unable to open downloaded file. Utf8 encoding error

### ISSUE THREAD

**Issue by oluomotoso** [Maatwebsite/Laravel-Nova-Excel#50]
### Versions

* PHP version: <7.2>
* Laravel version: <5.7>
* Nova version: <1.0>
* Package version: 

### Description

The file downloaded is not opening. Giving a UTF8 Malformed error
![image](https://user-images.githubusercontent.com/6395682/56619246-d3339000-661c-11e9-9112-b65f83b67325.png)

### Steps to Reproduce
Expected File to Open but giving error

**Expected behavior:**

**Actual behavior:** 

### Additional Information
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by patrickbrouwers** [comment]
Hey @oluomotoso it looks like one of your PHP-files has some output before the `<?php` opening tag. 

If that's not the case, make sure the filename is ascii encoded. (See warning in Laravel docs: https://laravel.com/docs/5.8/responses#file-downloads)
