### ISSUE TITLE
[BUG] Wrong order of columns

### ISSUE THREAD

**Issue by mizmiz** [Maatwebsite/Laravel-Nova-Excel#59]
### Prerequisites

* [ ] Able to reproduce the behaviour outside of your code, the problem is isolated to Laravel Excel.
* [x] Checked that your issue isn't already filed.
* [x] Checked if no PR was submitted that fixes this problem.

### Versions

* PHP version: 7.2.20
* Laravel version: 5.8.31
* Nova version: 2.0.10
* Package version: 3.1.15 / 1.1.5

### Description

Wrong order of columns in exported excel

### Steps to Reproduce

1. Config Excel Export as following:
```
(new DownloadExcel)
                ->only([
                    'title',
                    'first_name',
                    'last_name',
                    'email'
                ])
                ->withHeadings([
                    'Title',
                    'Vorname',
                    'Nachname',
                    'E-Mail'
                ])
                ->askForWriterType()
````
2. Export as XLS in Nova

**Expected behavior:**

Order of Data Excel file is: title, first_name, last_name, email

**Actual behavior:** 

Order of Data Excel file is: first_name, last_name, title, email

### Additional Information

Order of headings is correct though.

I think the problem is in vendor/maatwebsite/laravel-nova-excel/src/Actions/ExportToExcel.php in replaceFieldValuesWhenOnResource() where the 'resourceFields' are always used first and then the 'only' fields.

### Possible solution ###

```
 protected function replaceFieldValuesWhenOnResource(Model $model, array $only = []): array
    {
        ...

        // Fix sorting
        $row = array_merge(array_flip($only), $row);

        return $row;
    }
```

or 

```
 protected function replaceFieldValuesWhenOnResource(Model $model, array $only = []): array
    {
        ...

        // Fix sorting
        uksort($row, function($key1, $key2) use ($only) {
            return (array_search($key1, $only) > array_search($key2, $only));
        });

        return $row;
    }
```

**Comment by patrickbrouwers** [comment]
Feel free to PR a solution that takes the order of columns into account when using the only method

**Comment by patrickbrouwers** [comment]
Fixed in next release
