### ISSUE TITLE
No file extension when using askForWriterType

### ISSUE THREAD

**Issue by ghost** [Maatwebsite/Laravel-Nova-Excel#61]
### Prerequisites

* [x] Able to reproduce the behaviour outside of your code, the problem is isolated to Laravel Excel.
* [ ] Checked that your issue isn't already filed.
* [ ] Checked if no PR was submitted that fixes this problem.

### Versions

* PHP version: 7.1.3
* Laravel version: 5.8
* Nova version: 2.0
* Package version: Laravel Excel: 3.1, Laravel Nova Excel: 1.1

### Description

I have the following in my `actions()` function:

    return [
        (new DownloadExcel())
            ->withFilename('documents')
            ->askForWriterType([
                Excel::XLSX => 'XLSX',
                Excel::CSV  => 'CSV',
                Excel::HTML  => 'HTML',
            ])
    ];

Instead of getting the filename I set within `withFilename` function followed by the extesion I selected in the dropdown menu, I get only `documents` without any extesion.

This is happening only when `askForWriterType` is used in combination with `withFilename` function.

I have seen in the documentation that when using `withFilename`, I should specify the file extension within the function parameter, like `withFilename('documents.html')`, but the file type beeing dynamic, how I can get what file type the user selected within the dropdown menu?

### Steps to Reproduce

Just add the above code in your Nova component.

**Expected behavior:**

The name of the file I want to download should be `documents.` followed by the extesion I selected in the dropdown list. For example, if I select `html`, I should get `documents.html`.

**Actual behavior:** 

Instead of getting the filename I set within `withFilename` function followed by the extesion I selected in the dropdown menu, I get only `documents` without any extesion.

**Comment by patrickbrouwers** [comment]
That's indeed currently not supported. Feel free to make a PR to add this.

**Comment by patrickbrouwers** [comment]
PR merged
