### ISSUE TITLE
Nova 2.1 support

### ISSUE THREAD

**Issue by coding-monkeys-bv** [Maatwebsite/Laravel-Nova-Excel#62]
Hi guys, 

Just a quick heads up, upgrading Nova to 2.1 fails because of this package does not support it yet.

**Comment by patrickbrouwers** [comment]
Can you be more specific at what doesn't work? The package doesn't have any version constraint on Laravel Nova.

**Comment by voicecode-bv** [comment]
Ah I noticed that you accept a * for version. In my composer I used 2.1. There was a bug in 2.0.10 which caused translated dashboards to crash. That's why I did not want to use the *.

All good now :)

* sorry posted this with my other github account.. :)
