### ISSUE TITLE
Translations 

### ISSUE THREAD

**Issue by ghost** [Maatwebsite/Laravel-Nova-Excel#68]
### Prerequisites
Nothing

### Versions
* PHP version: 7.3.9 
* Laravel version: 5.8
* Nova version: 2.4
* Package version: 1.1

### Description
Can you add translation option, so I can translate the field and the action label

Fields names

I created a PR to fix this [PR LINK](https://github.com/Maatwebsite/Laravel-Nova-Excel/issues/68)
Thank you

**Comment by patrickbrouwers** [comment]
Fixed in next release
