### ISSUE TITLE
About Exporting Select All

### ISSUE THREAD

**Issue by hendrasan** [Maatwebsite/Laravel-Nova-Excel#7]
When you select all and then export, will it be **all records in the database** or just all records shown in the current page?

**Comment by patrickbrouwers** [comment]
Select all = current page
Select all matching = all in database (matching the indexQuery)

**Comment by Naoray** [comment]
When you select `Select all ` in a `Lens` view nothing will be exported. Only when you select `Select all matching` it will export the selected data to excel.
