### ISSUE TITLE
BUG: InvalidArgumentException - Unable to resolve NULL driver

### ISSUE THREAD

**Issue by chorton** [Maatwebsite/Laravel-Nova-Excel#71]
### Prerequisites

* [ x ] Able to reproduce the behaviour outside of your code, the problem is isolated to Laravel Excel.
* [ x ] Checked that your issue isn't already filed.
* [ x ] Checked if no PR was submitted that fixes this problem.

### Versions

* PHP version: 7.3.11
* Laravel version: 6.5.1
* Nova version: 2.7.0
* Package version: excel: 3.1.17 , laravel-nova-excel: 1.1.7

### Description

Receiving a 500 InvalidArgumentException exception when trying to export.
```
exception: "InvalidArgumentException"
file: "....../vendor/laravel/framework/src/Illuminate/Support/Manager.php"
line: 81
message: "Unable to resolve NULL driver for [Maatwebsite\Excel\Transactions\TransactionManager]."
```
### Steps to Reproduce

Go to resource, select all matching, select `Download Excel`, then the "play button", then in the confirm modal, click `Run Action`.

**Expected behavior:**

File downloads with all records

**Actual behavior:** 

Error as noted above (taken from the Network tab of debug console XHR request).  See screenshot
<img width="1061" alt="Screen Shot 2019-11-25 at 12 35 12 PM" src="https://user-images.githubusercontent.com/513859/69575982-3d7c2c80-0f80-11ea-9af8-c63589d82a72.png">

### Additional Information

N/A

**Comment by patrickbrouwers** [comment]
Wrong config setting in `config/excel.php` should be `'null`' not `'NULL'` for transaction driver
