### ISSUE TITLE
[BUG] Can't export using QueuedExport

### ISSUE THREAD

**Issue by turtlechase** [Maatwebsite/Laravel-Nova-Excel#76]
### Prerequisites

* [X] Able to reproduce the behaviour outside of your code, the problem is isolated to Laravel Excel.
* [X] Checked that your issue isn't already filed.
* [X] Checked if no PR was submitted that fixes this problem.

### Versions

* PHP version: 7.3.13
* Laravel version: 6.12.0
* Nova version: 2.9.4
* Package version: Excel 3.1.18 / Nova Excel 1.1.8

### Description

Error when using `QueuedExport`.

### Steps to Reproduce

Add `new QueuedExport()` to a resources actions function.
Select 1 or more rows on Nova and select Export to Excel action.

**Expected behavior:**

Export successfully to disk.

**Actual behavior:** 

Get error

> message: "Call to a member function forPage() on null"
exception: "Symfony\Component\Debug\Exception\FatalThrowableError"
file: "/var/www/html/vendor/maatwebsite/excel/src/Jobs/AppendQueryToSheet.php"
line: 92

<img width="779" alt="Screenshot 2020-01-28 at 12 58 29" src="https://user-images.githubusercontent.com/728008/73265997-ed168a80-41cd-11ea-9fdb-f22d6aa35222.png">

### Additional Information

None.

**Comment by patrickbrouwers** [comment]
Try to install 1.1.9 , it was released a few weeks ago

**Comment by turtlechase** [comment]
Oh that worked. I don't know why I was doing `composer update` and I wasn't getting latest version..

Even tho on composer I have `"maatwebsite/laravel-nova-excel": "^1.1"`
Had do specify 1.1.9.

Solved. Thanks
