### ISSUE TITLE
Interface WithCustomChunkSize not found

### ISSUE THREAD

**Issue by franzdumfart** [Maatwebsite/Laravel-Nova-Excel#8]
Thanks so much for the great plugin! Unfortunately I have problems setting it up on my Users resource. Did I miss something?

![screen shot 2018-08-30 at 14 38 08](https://user-images.githubusercontent.com/1145410/44851995-55bca900-ac62-11e8-9b39-1c3598c6f214.png)

Is Laravel-Excel a dependency? It's not in my project. Could be the issue, right?

**Comment by patrickbrouwers** [comment]
@franzdumfart It should install Maatwebsite/Excel by default. This concern was added in .3.0.10, perhaps you can check which version it installed.

**Comment by franzdumfart** [comment]
Okay this isn't the problem, sorry. Version 1.0 is installed and I also have the Maatwebsite/Excel dependency.

**Comment by patrickbrouwers** [comment]
Which version of Maatwebsite/Excel  is in your composer.lock ?

Can you try to install `1.0.1` of this package. It bumps the minimum version of excel to 3.0.10 .

**Comment by franzdumfart** [comment]
Works now! Thanks :)

**Comment by patrickbrouwers** [comment]
Great!
