### ISSUE TITLE
[BUG/QUESTION] Error 403 invalid siganture

### ISSUE THREAD

**Issue by jlballes** [Maatwebsite/Laravel-Nova-Excel#83]
### Prerequisites

* [ ] Able to reproduce the behaviour outside of your code, the problem is isolated to Laravel Excel.
* [x] Checked that your issue isn't already filed.
* [x] Checked if no PR was submitted that fixes this problem.

### Versions

* PHP version: 7.2.27
* Laravel version: 6.18.0
* Nova version: 2.10.0
* Package version: Laravel Excel 3.1.19,  Laravel Nova Excel 1.2.1

### Description

The package is working perfectly in my local environment but when I deploy my app into my acceptance environment in Azure and I try to download an excel I can see a "403 error - invalid signature" in the Firefox inspector -  network, so the file is not downloaded. In all web browsers the file is not downloaded. 

When you run the "Download excel" Action the first request returns 200, but in the second request, Laravel is returning 403 invalid signature, so the file is not downloaded.

So it seems that is not a package bug and it is related with Azure, but maybe someone knows what is happening.

WORK AROUND: I have created a custom action (following the documentation: https://docs.laravel-excel.com/nova/1.1/exports/customizations.html#full-control).
Then I have overwrite the method "getDownloadUrl" in order to generate an URL without signature and in order to use a custom controller to avoid the signed middleware:

`protected function getDownloadUrl(BinaryFileResponse $response): string
    {
        return route('your-route.name', [
          'path'     => encrypt($response->getFile()->getPathname()),
          'filename' => $this->getFilename(),
        ]);
    }`

With this solution it is working in Azure.

Any idea?
Thank you so much.

**Comment by monooso** [comment]
I just ran into a similar issue on a local development site. In my case, it seems to be caused by the [HTTPS Everywhere](https://www.eff.org/https-everywhere) browser extension (the local site uses HTTP).

Everything works perfectly when using a "fresh" browser profile, with no extensions installed.

**Comment by j0n17** [comment]
I stumbled upon a similar issue, in my case, my Laravel was behind a reverse proxy (with SSL termination).
What did it for me was to configure the trusted proxies which I forgot (see https://laravel.com/docs/8.x/requests#configuring-trusted-proxies).

**Comment by patrickbrouwers** [comment]
As said in different issues, it's often due to a mix of using http and https. Or indeed a reverse proxy could be the cause.

**Comment by jehkinen** [comment]
Seems like more easy to create custom export then debug this nova stuff which comes with bugs in box as usual
