### ISSUE TITLE
[BUG] The given value "" does not represent a valid number

### ISSUE THREAD

**Issue by ejntaylor** [Maatwebsite/Laravel-Nova-Excel#84]
* [ ] Able to reproduce the behaviour outside of your code, the problem is isolated to Laravel Excel.
* [x ] Checked that your issue isn't already filed.
* [ x] Checked if no PR was submitted that fixes this problem.

### Versions

* PHP version: php7.4
* Laravel version: laravel 7.2
* Nova version: 2.0
* Package version: 1.2.1

### Description

Cannot download as get an error.

### Steps to Reproduce

Select items, choose Download Excel then click Run Action

**Expected behavior:**

Download file.

**Actual behavior:** '

![image](https://user-images.githubusercontent.com/2080025/77649813-59a9cd80-6f62-11ea-8e16-a7cbc0b8a7fd.png)

![image](https://user-images.githubusercontent.com/2080025/77649833-64fcf900-6f62-11ea-91f6-bf84e83928ae.png)

ERROR MESSAGE: 500 CODE : 
message: The given value "" does not represent a valid number.
exception: Brick\Math\Exception\NumberFormatException
file: /Users/ejntaylor/Documents/Laravel/sqft/vendor/brick/math/src/BigNumber.php
line: 75

### Additional Information

This only has a problem on a resource using currency. 

see my fields here:

   ```
         Date::make('created_at')->sortable(),
            ID::make()->sortable(),
            Status::make('status')
                ->loadingWhen(['waiting', 'running'])
                ->failedWhen(['failed']),
            Currency::make('a')->sortable(),
            Currency::make('b')->currency('GBP')->sortable(),
            Currency::make('c')->sortable()->hideFromIndex(),
            Currency::make('d')->sortable()->hideFromIndex(),
            Currency::make('e')->sortable()->hideFromIndex(),
            Text::make('f')->sortable()->hideFromIndex(),
            Text::make('g')->sortable()->hideFromIndex(),
            Text::make('h')->sortable()->hideFromIndex(),
            Text::make('i')->sortable()->hideFromIndex(),
            Text::make('j')->sortable()->hideFromIndex(),
            BelongsTo::make('User')->nullable()
```

**Comment by calvinmuller** [comment]
Same issue - works if I remove `withHeadings()` from export

**Comment by h9k** [comment]
This was driving me crazy, but thankfully I know how to use Google :)
@calvinmuller I can confirm that removing withHeadings() makes the export work.

**Comment by ejntaylor** [comment]
Same issue but the current solution is not suitable if you want the export to include headings...

**Comment by xmarkclx** [comment]
Removing withHeadings() doesn't work for me.
Anyway, after digging a bit with XDebug and moving around the source code.

I found a solution that doesn't need to modify any of the sources or make a PR, just 

- make a custom mapping import and 
- in the Nova Model, add an if statement like below.

```php
if ($request->action == 'download-excel') {
            /**
             * Solution for bug: https://github.com/Maatwebsite/Laravel-Nova-Excel/issues/84.
             */
            return [];
        }
```

ex.

```php
    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        if ($request->action == 'download-excel') {
            /**
             * Solution for bug: https://github.com/Maatwebsite/Laravel-Nova-Excel/issues/84.
             */
            return [];
        }
        return [
            Text::make(__('Name'), 'name')
                ->rules('required', 'max:255')
                ->sortable(),
```

This should make the exporter not have to enumerate the fields and get into random and unnecessary exceptions.

**Comment by IGedeon** [comment]
I found this is a Laravel Nova Issue with the currency field

https://github.com/laravel/nova-issues/issues/2372

It will be fixed in the next release

**Comment by Wenuz** [comment]
If you replace all your "Currencies" with "Number", it works, I think the package does not support the Nova "Currency".

**Comment by patrickbrouwers** [comment]
Will close this ticket, as the bug is fixed in Nova
