### ISSUE TITLE
[QUESTION] Full control not downloading excel file

### ISSUE THREAD

**Issue by jaap115** [Maatwebsite/Laravel-Nova-Excel#87]
* [ ] Able to reproduce the behaviour outside of your code, the problem is isolated to Laravel Excel.
* [x ] Checked that your issue isn't already filed.
* [x ] Checked if no PR was submitted that fixes this problem.

* PHP version: 7.2
* Laravel version: 7
* Nova version: 3
* Package version: 1.2

### Description

I build a custom action for downloading invoices for a specific user. The person downloading needs to be able to select the invoices. But the actual data that is required (amounts, Vat etc) is in another table. So I created a custom handle function for that part. My problem is when I run this action the request returns the data correctly as a response but there is no download triggering. I think I'm missing something but I can't google out what it is.
```

<?php

namespace App\Nova\Actions;

use Laravel\Nova\Actions\Action;
use Laravel\Nova\Http\Requests\ActionRequest;
use Maatwebsite\LaravelNovaExcel\Actions\DownloadExcel;
use Maatwebsite\Excel\Concerns\FromArray;
use App\Models\App\AppInvoice;

class DownloadInvoices extends DownloadExcel implements FromArray
{
    protected $invoices = [];
    /**
     * @param ExportActionRequest $request
     * @param Action              $exportable
     *
     * @return array
     */
    public function handle(ActionRequest $request, Action $exportable): array
    {
        $models = $exportable->query()->with('invoiceItems')->get()->toArray();
        foreach ($models as $model) {
            foreach ($model['invoice_items'] as $item) {
                $this->invoices[] = [
                    'Bedrag' => $item['price'],
                    'Factuurnummer' => $model['invoice_number']
                ];
            }

        }
        return $this->array();
    }

    /**
     * @inheritDoc
     */
    public function array(): array
    {
        return $this->invoices;
    }
}

```
### Steps to Reproduce

Create custom action with this type of handle function

**Expected behavior:**

Download a file with my custom array

**Actual behavior:** 

Action returns array as a response but does not trigger a download.

**Comment by jaap115** [comment]
Is there somebody who can help me with this?

**Comment by runand** [comment]
@jaap115 By just looking at it, you override the handle method, but in the handle method on the DownloadExcel it returns the Action::download, I guess you should implement something similar in your handle method

**Comment by patrickbrouwers** [comment]
As runand said, make sure to correctly override the handle method and returning the same response.
