### ISSUE TITLE
[BUG] Wrong default fields in exported excel

### ISSUE THREAD

**Issue by rgavril** [Maatwebsite/Laravel-Nova-Excel#89]
### Prerequisites

* [X] Able to reproduce the behaviour outside of your code, the problem is isolated to Laravel Excel.
* [X] Checked that your issue isn't already filed.
* [X] Checked if no PR was submitted that fixes this problem.

### Versions

* PHP version: 7.4.5
* Laravel version: 7.6.2
* Nova version: 3.3.2
* Package version: 1.2.1 / 3.1.19
### Description

When doing an export I expect to see the same fields as in the they are on the nova resource index table. 

Apparently if the  _fieldsForIndex()_ method is present it doesn't take precedence over the _fields()_ resulting different format in the generated excel file compared to what I see on the screen.

This can be seen also as a feature as sometimes is useful to be able to define different fields for the exported excel but I don't think that the plugin should behave like this by default.

### Steps to Reproduce

Return different fields in _fieldsForIndex()_ and _fields()_

**Expected behavior:**

When doing a excel export I should see the fields defined in _fieldsForIndex()_

**Actual behavior:** 

When doing a excel export I see the fields defined in _fields()_

**Comment by patrickbrouwers** [comment]
Yeah I don't think we currently do anything with that. I actually haven't even heard of it. Feel free to PR a solution.

In the future I would like a solution where we can include/exclude fields from export. `Text::make()->excludeFromExport()` But that won't be for soon
