### ISSUE TITLE
Exception: Directory "/tmp" was not created

### ISSUE THREAD

**Issue by 4n70w4** [Maatwebsite/Laravel-Nova-Excel#95]
But why use `/tmp` directory instead of a standard Laravel storage directory?

There is also no information in your documentation that the `/tmp` directory is used.

**Comment by patrickbrouwers** [comment]
Configuration defaults to `sys_get_temp_dir`, it's the default system dir. You can change it to whatever you prefer: https://github.com/Maatwebsite/Laravel-Excel/blob/3.1/config/excel.php#L166

**Comment by 4n70w4** [comment]
Okay. I run:

```php
php artisan vendor:publish --provider="Maatwebsite\Excel\ExcelServiceProvider"
```


Open `config/excel.php` and comment line 166:

```php
// 'local_path'  => '',
```

Then generated file `/var/www/app/storage/framework/laravel-excel/laravel-excel-rLvinX8hLlU9XHIpkfn6cA28zIkEidzK`


`/nova-api/expertises/action?action=download-excel&pivotAction=false&search=&filters=&trashed=`

returns

```json
{"download":"https:\/\/XXX\/nova-vendor\/maatwebsite\/laravel-nova-excel\/download?expires=1594134239&filename=resources.xlsx&path=eyJpdiI6IlJNQTMwdk9iclwvejVqb3VsNGlHNHhRPT0iLCJ2YWx1ZSI6Ik5GVlREWHIzRlJ0RlNlOWpVbEk3eXlVNjdKS3hIczVwbmZhOEFYXC9hWmJwdWt5N0NOc0ozKzN3OWlxRitwYkxyNTIxcWRQRkFWXC9TV3dsRG9TeHVoMlpIRXNmd0V4WWtmOEl5djE4Q0R5RkdMb3B0V3Naa0J5ajBkcjZlY1ZjeEc2OWhNYXY2K05pcUVURW12MTN5SUVBPT0iLCJtYWMiOiI0YTQ3Y2M5NTgyZjAxMTg0YWUyMWJkYmM4MDhhMGE1MWYyNTU0ZWZkNjY4ZTVjMjBjY2JlOWQ2YTllMTViMWYyIn0%3D&signature=d4fbb34f5e8a18aa131a16d18352f0e09553805a0218a3c60383f05e887518a3","name":"resources.xlsx"}
```

But this link gets error 403 Invalid signature.

**Comment by patrickbrouwers** [comment]
I don't think you can comment that line, you have to fill in a value there like `storage_path('excel')`

**Comment by patrickbrouwers** [comment]
For the signature make sure you sign with `https` enabled in your app. Because you cannot open it if you signed with http, but open with https

**Comment by 4n70w4** [comment]
@patrickbrouwers `vendor/maatwebsite/excel/src/ExcelServiceProvider.php:54`

```php
            return new TemporaryFileFactory(
                config('excel.temporary_files.local_path', config('excel.exports.temp_path', storage_path('framework/laravel-excel'))),
                config('excel.temporary_files.remote_disk')

            );
```

This code generated default path. I comment `local_path` so that the default value is generated. It suits me.


The links show that they are `https`. `APP_URL` also with `https`. Also ` \URL::forceScheme('https');`.

I have no more ideas how else to enable `https` in app.

**Comment by patrickbrouwers** [comment]
Maybe you have a middleware that changes the url before the signature is checked

**Comment by 4n70w4** [comment]
Okay. I use reverse proxy. Need configure `fideloper/proxy`.

```php
php artisan vendor:publish --provider="Fideloper\Proxy\TrustedProxyServiceProvider"
```

Edit `config/trustedproxy.php` line 18:

```php
    'proxies' => '*', // [<ip addresses>,], '*', '<ip addresses>,'
```

**Comment by 4n70w4** [comment]
@patrickbrouwers thanks for the support and quick answers.
